### PR TITLE
fix: use default low maintenance level in calculateFairhold

### LINKED ISSUE #468: Bug: Make sure house price shows default low, and not the user selected maintenance level

### PR DESCRIPTION
**Pull request by zz-hh-aa**
Fixes bug where the user selected maintenance level was being used to calculate `depreciatedBuildPrice` (instead of our default `low`). User selected maintenance level should only be used in the resale value highlight graph. 

Closes #468

### CODE REVIEW

File: app/models/Property.ts [hunk 1]
```diff
@@ -94,22 +97,23 @@ export class Property {
...
-    depreciatedBuildPrice = parseFloat(depreciatedBuildPrice.toFixed(PRECISION))
-  return depreciatedBuildPrice;
+    // Calculate for each component using the public method
+    for (const key of Object.keys(HOUSE_BREAKDOWN_PERCENTAGES) as (keyof houseBreakdownType)[]) {
+      const result = this.calculateComponentValue(
+        key, 
+        this.newBuildPrice, 
+        this.age, 
+        "low" // `calculateDepreciatedBuildPrice` is only used in `Property` and not in `Lifetime`, so we can use the default value for maintenanceLevel
+      );
```
Comment (DafyddLlyr) [inline app/models/Property.ts:111]: This might be better / clearer / more readable as single options object as an argument, with "low" as a default value.

```ts
// Definition
public calculateComponentValue(
  {
    componentKey,
    newBuildPrice,
    age,
    maintenanceLevel = "low",
  }: {
    componentKey: keyof houseBreakdownType;
    newBuildPrice: number;
    age: number;
    maintenanceLevel?: MaintenanceLevel;
  }
): ComponentCalculation {
...
}

// Execution
const result = this.calculateComponentValue({
  componentKey: key,
  newBuildPrice: this.newBuildPrice,
  age: this.age,
});
```

**Review by DafyddLlyr — APPROVED** [review]

File: app/models/Property.ts (hunk 1 above)
Comment (zz-hh-aa) [reply app/models/Property.ts]: Tidy--though in doing this I realised it didn't need to be an arg anyway, since we're not reusing this function anywhere else (we can access `low` from directly within it). Done in [246332b](https://github.com/theopensystemslab/fairhold-dashboard/pull/479/commits/246332bc792400654b53dfcb7081d11a9b4e9e81)
